default:
  dora_dir: /mnt/backgroundscore-sg/tmp/audiocraft_${oc.env:USER}
  partitions:
    global: debug
    team: debug
  reference_dir: /mnt/backgroundscore-sg/tmp
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /mnt/backgroundscore-sg/tmp/audiocraft_${oc.env:USER}
  partitions:
    global: debug
    team: debug
  reference_dir: /mnt/backgroundscore-sg/tmp
